version: '3' 
services: 
        worker: 
                build: 
                        context: . 
                        dockerfile: Dockerfile 
                environment: 
                        - POSTGRESQL_HOST=database-postgres-tjg.cvb1csfwepbn.us-east-1.rds.amazonaws.com
                        - POSTGRESQL_USER=postgres
                        - POSTGRESQL_PASSWORD=passwordpassword
                        - POSTGRESQL_DATABASE=operational_tjg
                        - BROKER_URL=amqps://username:passwordpassword@b-7182fca9-4c07-4bfa-be01-72310cb18d60.mq.us-east-1.amazonaws.com:5671
                image: taesb 
                command: ['celery', '-A', 'taesb', 'worker', '-l', 'INFO'] 

