""" 
Process the data generated by the simulation with Spark's Python API.
""" 
# The application 
import taesb 
from taesb.spark.SparkSubmit import ScheduleSpark 

# Interval between subsequent processing (in seconds) 
INTERVAL = 9

if __name__ == "__main__": 
    spark = ScheduleSpark(app_name="taesb") 
    # Start the processing 
    spark.schedule(stamp=INTERVAL)
